server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: Pratik@19
    driver-class-name: org.postgresql.Driver

  jpa:                          # <-- moved out, now aligned with datasource
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8083/eureka/

app:
  security:
    jwt-service-id: JWTSERVICE
